[auth]
cookie_name = "goat_auth"
cookie_ttl_days = 7

[auth.users]
admin = "$2b$12$LLKUwkg8dwfH7CigVpWOGeJro9buRxeaX1diIGjbo/ZAlaXWCSMnS"
goat  = "$2b$12$mSlMDeNAblOO.Ma58YzmEe961CXIRn9YjhNtQ6275HjsDNb1U/UVi"
juan  = "$2b$12$yn9tx8eMmRSQCHzsM3tPJ.ATEHQ4L2hhKvbCcJ2pyGPsCpj/sWDZu"